name: HumanAngel
version: 1.3
main: com.humanangel.Main
api-version: 1.21
commands:
  mode: { description: "ADM" }
  control: { description: "ADM" }
  sc: { description: "ADM" }
  ha: { description: "ADM" }
  zoeira: { description: "ADM - Avisos 2h" }
  angelwand: { description: "ADM - Tridente" }
  set: { description: "ADM - WorldEdit" }
  paredes: { description: "ADM - WorldEdit" }
  home: { description: "Player" }
  sethome: { description: "Player" }
  tpa: { description: "Player" }
  tpaccept: { description: "Player" }
  pvp: { description: "Player" }
  spawn: { description: "Player" }
  tamanho: { description: "Player" }
  
