name: HumanAngel
version: 1.2
main: com.humanangel.Main
api-version: 1.21
commands:
  sc:
    description: "Chat exclusivo para a staff."
  spawn:
    description: "Teleporta para o ponto inicial."
  mode:
    description: "Muda o modo de jogo rapido (c,s,a,sp)."
  tamanho:
    description: "Altera a escala do jogador."
  pvp:
    description: "Ativa ou desativa o combate global."
  angelwand:
    description: "Pega o Tridente Arcanjo para edicao."
  control:
    description: "Abre o menu de controle de jogadores."
  clearlag:
    description: "Limpa os itens do chao manualmente."
  ha:
    description: "Comando principal do plugin."
    
