name: HumanAngel
version: 1.6
main: com.humanangel.Main
api-version: 1.21
commands:
  ha:
    description: Status
  modo:
    description: Alternar gamemodes (c, s, a, sp)
  home:
    description: Ir home
  sethome:
    description: Setar home
  spawn:
    description: Spawn
  set:
    description: Fill
  paredes:
    description: Walls
  angelwand:
    description: Wand
  control:
    description: Ver inventarios
  lista:
    description: Ver comandos
  clearlag:
    description: Limpar chao
  tpa:
    description: Pedir teleporte
  tpaccept:
    description: Aceitar teleporte
  tpdeny:
    description: Recusar teleporte
  zueira:
    description: Filtro de palavras
  avisos:
    description: Mensagens automaticas
    
